# root = File.expand_path File.dirname(__FILE__)
# require File.join( root , 'applies.rb' )
# require File.join( root , 'companies.rb' )
# require File.join( root , 'geeks.rb' )
# require File.join( root , 'jobs.rb' )